name: pronote_dart
description: A PRONOTE® API wrapper written in Dart
version: 1.0.0
repository: https://github.com/Skythrew/pronote_dart

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  encrypt: ^5.0.3
  hex: ^0.2.0
  crypto: ^3.0.6
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
